import { Helmet } from "react-helmet-async";

export default function TermsPage() {
  return (
    <div className="container max-w-4xl py-16 md:py-24">
      <Helmet>
        <title>Terms and Conditions — Product Nerve AI</title>
        <meta name="description" content="Product Nerve AI Terms and Conditions." />
        <link rel="canonical" href="https://productnerve.com/terms-and-conditions" />
      </Helmet>

      <h1 className="text-3xl md:text-4xl font-bold mb-2 text-foreground">Terms and Conditions</h1>
      <p className="text-muted-foreground mb-10">Last Updated: March 8th, 2026</p>

      <div className="space-y-10 text-foreground/90 leading-relaxed">
        <Section title="1. Acceptance of Terms">
          <p>By accessing or using Product Nerve AI, you agree to comply with these Terms and Conditions.</p>
          <p>If you do not agree, you must discontinue use of the platform.</p>
        </Section>

        <Section title="2. Description of Services">
          <p>Product Nerve AI provides digital tools designed to help entrepreneurs and businesses:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Validate business ideas</li>
            <li>Design execution strategies</li>
            <li>Generate growth frameworks</li>
            <li>Analyze startup data</li>
            <li>Create strategic documentation</li>
          </ul>
          <p>The platform provides analytical tools and AI-generated insights.</p>
          <p className="text-muted-foreground italic">These services do not constitute financial, legal, or investment advice.</p>
        </Section>

        <Section title="3. User Responsibilities">
          <p>Users agree to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Provide accurate information</li>
            <li>Maintain account security</li>
            <li>Use the platform lawfully</li>
            <li>Avoid misuse or abuse of the system</li>
          </ul>
          <p className="mt-3">Users must not attempt to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Reverse engineer platform systems</li>
            <li>Exploit vulnerabilities</li>
            <li>Access unauthorized data</li>
            <li>Distribute harmful or illegal content</li>
          </ul>
        </Section>

        <Section title="4. Intellectual Property">
          <p>All intellectual property related to the Product Nerve AI platform, including:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Software</li>
            <li>Algorithms</li>
            <li>Branding</li>
            <li>System architecture</li>
            <li>User interface</li>
            <li>Proprietary models</li>
          </ul>
          <p>remains the exclusive property of Product Nerve AI.</p>
          <p className="font-semibold">Users retain ownership of the data they upload to the platform.</p>
        </Section>

        <Section title="5. AI Generated Outputs">
          <p>Insights generated by Product Nerve AI are provided for informational purposes.</p>
          <p>Users are responsible for decisions made based on these outputs.</p>
          <p className="text-muted-foreground italic">Product Nerve AI does not guarantee business outcomes or financial success.</p>
        </Section>

        <Section title="6. Account Termination">
          <p>We reserve the right to suspend or terminate accounts if users:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Violate these Terms</li>
            <li>Engage in abusive or fraudulent behavior</li>
            <li>Attempt unauthorized access</li>
          </ul>
        </Section>

        <Section title="7. Limitation of Liability">
          <p>Product Nerve AI shall not be liable for:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Business losses</li>
            <li>Financial losses</li>
            <li>Investment decisions</li>
            <li>Indirect damages</li>
          </ul>
          <p>resulting from use of the platform.</p>
        </Section>

        <Section title="8. Governing Law">
          <p>These Terms may be governed by applicable international commercial laws depending on the jurisdiction of service usage.</p>
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-xl font-bold mb-3 text-foreground">{title}</h2>
      <div className="space-y-3 text-sm md:text-base">{children}</div>
    </section>
  );
}
