import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { FileText, BookOpen, Users, FlaskConical, TrendingUp, Map, ExternalLink, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { useWorkspace } from "@/contexts/WorkspaceContext";

interface Artifact {
  _id: string;
  id?: string;
  title: string;
  status: string;
  project_id?: { _id: string; name: string } | string | null;
  workspace_id?: { _id: string; name: string } | string;
  createdAt: string;
  updatedAt: string;
  type?: string;
}

const TOOL_TABS = [
  { key: "prd", label: "PRDs", icon: FileText, table: "prd_documents" as const },
  { key: "stories", label: "User Stories", icon: BookOpen, table: "user_stories" as const },
  { key: "icp", label: "ICP Profiles", icon: Users, table: "icp_profiles" as const },
  { key: "experiments", label: "Experiments", icon: FlaskConical, table: "experiments" as const },
  { key: "growth", label: "Growth Plans", icon: TrendingUp, table: "growth_plans" as const },
  { key: "roadmaps", label: "Roadmaps", icon: Map, table: "roadmaps" as const },
];

const API_BASE_URL = import.meta.env.VITE_API_URL;

export default function StudioArtifactsPage() {
  const navigate = useNavigate();
  const { activeWorkspace } = useWorkspace();
  const [artifacts, setArtifacts] = useState<Record<string, Artifact[]>>({});
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState("prd");

  useEffect(() => {
    loadAllArtifacts();
  }, [activeWorkspace]);

  const loadAllArtifacts = async () => {
    if (!activeWorkspace) return;
    
    setLoading(true);
    try {
      const token = localStorage.getItem('token');
      const workspaceId = activeWorkspace._id || activeWorkspace.id;
      
      const response = await fetch(`${API_BASE_URL}/artifacts?workspace_id=${workspaceId}`, {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      
      if (response.ok) {
        const data = await response.json();
        const formattedArtifacts: Record<string, Artifact[]> = {
          prd: data.data.prd.artifacts || [],
          stories: data.data.stories.artifacts || [],
          icp: data.data.icp.artifacts || [],
          experiments: data.data.experiments.artifacts || [],
          growth: data.data.growth.artifacts || [],
          roadmaps: data.data.roadmaps.artifacts || []
        };
        setArtifacts(formattedArtifacts);
      } else {
        const error = await response.json();
        toast.error(error.error || "Failed to load artifacts");
      }
    } catch {
      toast.error("Network error while loading artifacts");
    } finally {
      setLoading(false);
    }
  };

  const deleteArtifact = async (type: string, id: string) => {
    try {
      const token = localStorage.getItem('token');
      const response = await fetch(`${API_BASE_URL}/artifacts/${type}/${id}`, {
        method: 'DELETE',
        headers: { 'Authorization': `Bearer ${token}` }
      });
      
      if (response.ok) {
        setArtifacts(prev => ({
          ...prev,
          [type]: prev[type].filter(a => (a._id || a.id) !== id)
        }));
        toast.success("Artifact deleted successfully");
      } else {
        const error = await response.json();
        toast.error(error.error || "Failed to delete artifact");
      }
    } catch {
      toast.error("Network error while deleting artifact");
    }
  };

  const getToolPath = (key: string) => {
    const map: Record<string, string> = {
      prd: "/app/studio/prd-generator",
      stories: "/app/studio/user-stories",
      icp: "/app/studio/icp-builder",
      experiments: "/app/studio/experiment-engine",
      growth: "/app/studio/growth-engine",
      roadmaps: "/app/studio/roadmap-generator",
    };
    return map[key] || "/app";
  };


  return (
    <div>
      <div className="mb-6">
        <h1 className="text-2xl font-bold">Studio Artifacts</h1>
        <p className="text-sm text-muted-foreground">All documents generated by Product Studio tools</p>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList className="flex flex-wrap gap-1 h-auto mb-6">
          {TOOL_TABS.map((tab) => (
            <TabsTrigger key={tab.key} value={tab.key} className="gap-1.5 text-xs">
              <tab.icon className="h-3.5 w-3.5" />
              {tab.label}
              {artifacts[tab.key] && (
                <span className="ml-1 text-[10px] bg-muted px-1.5 rounded-full">{artifacts[tab.key].length}</span>
              )}
            </TabsTrigger>
          ))}
        </TabsList>

        {TOOL_TABS.map((tab) => (
          <TabsContent key={tab.key} value={tab.key}>
            {loading ? (
              <div className="flex justify-center py-12">
                <div className="h-6 w-6 border-2 border-accent border-t-transparent rounded-full animate-spin" />
              </div>
            ) : (artifacts[tab.key] || []).length === 0 ? (
              <div className="text-center py-12 text-muted-foreground">
                <tab.icon className="h-8 w-8 mx-auto mb-2 opacity-40" />
                <p className="text-sm">No {tab.label.toLowerCase()} yet.</p>
                <Button variant="outline" size="sm" className="mt-3" onClick={() => navigate(getToolPath(tab.key))}>
                  Create One
                </Button>
              </div>
            ) : (
              <div className="space-y-2">
                {(artifacts[tab.key] || []).map((a) => (
                  <div key={a._id || a.id} className="flex items-center gap-3 p-3 rounded-lg bg-muted/50 hover:bg-muted transition-colors">
                    <tab.icon className="h-4 w-4 text-accent shrink-0" />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium truncate">{a.title}</p>
                      <p className="text-[10px] text-muted-foreground">
                        {new Date(a.createdAt || a.updatedAt).toLocaleDateString()} • {a.status}
                      </p>
                    </div>
                    <div className="flex gap-1">
                      <Button variant="ghost" size="sm" className="h-7 w-7 p-0" onClick={() => navigate(`${getToolPath(tab.key)}/${a._id || a.id}`)}>
                        <ExternalLink className="h-3.5 w-3.5" />
                      </Button>
                      <Button variant="ghost" size="sm" className="h-7 w-7 p-0 text-destructive" onClick={() => deleteArtifact(tab.key, a._id || a.id)}>
                        <Trash2 className="h-3.5 w-3.5" />
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </TabsContent>
        ))}
      </Tabs>
    </div>
  );
}
