import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  BarChart3, Users, FileText, FlaskConical, Map, BookOpen, Target, TrendingUp
} from "lucide-react";
import {
  PieChart, Pie, Cell, ResponsiveContainer, LineChart, Line, XAxis, YAxis,
  CartesianGrid, Tooltip, Legend, BarChart, Bar
} from "recharts";
import { format, subDays } from "date-fns";
import AdminApiService from "@/services/adminApi";
import { toast } from "sonner";

const TOOL_COLORS = ["#0F555A", "#E77023", "#10b981", "#6366f1", "#f59e0b", "#ec4899"];
const TOOL_LABELS: Record<string, string> = {
  icp_profiles: "ICP Builder",
  experiments: "Experiment Engine",
  growth_plans: "Growth Engine",
  roadmaps: "Roadmap Generator",
  user_stories: "User Story Generator",
  prd_documents: "PRD Generator",
};

export default function StudioAnalyticsPage() {
  const [data, setData] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    const fetchStudioAnalytics = async () => {
      setIsLoading(true);
      try {
        const response = await AdminApiService.getStudioAnalytics();
        if (response.success) {
          setData(response.data);
        } else {
          toast.error("Failed to load studio analytics");
        }
      } catch (error) {
        toast.error("Error loading studio analytics");
      } finally {
        setIsLoading(false);
      }
    };

    fetchStudioAnalytics();
  }, []);

  const { toolCounts, studioUsers, aiUsage } = data || {};

  const totalDocs = toolCounts ? Object.values(toolCounts).reduce((a: number, b: any) => a + (b as number), 0) : 0;

  const pieData = toolCounts
    ? Object.entries(toolCounts).map(([key, value]) => ({ name: TOOL_LABELS[key] || key, value }))
    : [];

  const stats = [
    { label: "Total Studio Users", value: studioUsers ?? 0, icon: Users },
    { label: "Total Documents", value: totalDocs, icon: FileText },
    { label: "Total AI Requests", value: aiUsage?.total ?? 0, icon: BarChart3 },
    { label: "Monthly AI Requests", value: aiUsage?.monthly ?? 0, icon: TrendingUp },
  ];

  const toolStats = [
    { label: "ICP Profiles", value: toolCounts?.icp_profiles ?? 0, icon: Target },
    { label: "Experiments", value: toolCounts?.experiments ?? 0, icon: FlaskConical },
    { label: "Growth Plans", value: toolCounts?.growth_plans ?? 0, icon: TrendingUp },
    { label: "Roadmaps", value: toolCounts?.roadmaps ?? 0, icon: Map },
    { label: "User Stories", value: toolCounts?.user_stories ?? 0, icon: BookOpen },
    { label: "PRDs", value: toolCounts?.prd_documents ?? 0, icon: FileText },
  ];

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-foreground">Product Studio Analytics</h1>
        <p className="text-muted-foreground text-sm">Monitor tool usage, adoption, and engagement across the platform.</p>
      </div>

      {/* Top Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {stats.map((s) => (
          <Card key={s.label}>
            <CardContent className="p-4 flex items-center gap-3">
              <div className="h-10 w-10 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                <s.icon className="h-5 w-5 text-primary" />
              </div>
              <div>
                <p className="text-2xl font-bold text-foreground">{s.value.toLocaleString()}</p>
                <p className="text-xs text-muted-foreground">{s.label}</p>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Tool Breakdown */}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
        {toolStats.map((s) => (
          <Card key={s.label}>
            <CardContent className="p-4 text-center">
              <s.icon className="h-5 w-5 mx-auto text-accent mb-1" />
              <p className="text-xl font-bold text-foreground">{s.value}</p>
              <p className="text-[11px] text-muted-foreground">{s.label}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Charts */}
      <div className="grid md:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Tool Usage Distribution</CardTitle>
            <CardDescription>Documents generated by tool type</CardDescription>
          </CardHeader>
          <CardContent>
            {(totalDocs as number) > 0 ? (
              <ResponsiveContainer width="100%" height={280}>
                <PieChart>
                  <Pie data={pieData} cx="50%" cy="50%" outerRadius={100} dataKey="value" label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}>
                    {pieData.map((_, i) => (
                      <Cell key={i} fill={TOOL_COLORS[i % TOOL_COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
            ) : (
              <p className="text-sm text-muted-foreground text-center py-16">No data yet</p>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-base">Studio Engagement Funnel</CardTitle>
            <CardDescription>User progression through the studio</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3 py-4">
              {[
                { label: "Studio Users", val: studioUsers ?? 0 },
                { label: "Documents Generated", val: totalDocs },
                { label: "AI Requests Made", val: aiUsage?.total ?? 0 },
              ].map((step, i) => (
                <div key={i} className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center text-xs font-bold text-primary">{i + 1}</div>
                  <div className="flex-1">
                    <div className="flex justify-between text-sm">
                      <span className="text-foreground">{step.label}</span>
                      <span className="font-semibold text-foreground">{step.val.toLocaleString()}</span>
                    </div>
                    <div className="h-2 bg-muted rounded-full mt-1 overflow-hidden">
                      <div
                        className="h-full bg-primary rounded-full transition-all"
                        style={{ width: `${Math.min(100, studioUsers ? (step.val / (studioUsers || 1)) * 100 : 0)}%` }}
                      />
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
